name: main

on: [push]

jobs:
  package:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ConsoleApp6
          path: ConsoleApp6
          
  notify:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get release version
        id: get_version
        uses: dawidd6/action-get-tag@v1

      - name: Notify Discord
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            {
              "ContentType": "application/json; charset=UTF-8"
            }
          payload: |
            {
              "content": "**ConsoleApp6** new version released"
            }
