name: main

on: [push]

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Get release version
        id: get_version
        uses: dawidd6/action-get-tag@v1

      - name: Notify Discord
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            {
              "ContentType": "application/json; charset=UTF-8"
            }
          payload: |
            {
              "content": "**AniStream** new version released!\nVersion: `${{ steps.get_version.outputs.tag }}`\Download: <https://github.com/jery08/AniStream/releases/download/AniStream-${{ steps.get_version.outputs.tag }}.apk>"
            }
