name: main

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            {
              "ContentType": "application/json; charset=UTF-8"
            }
          payload: |
            {
              "content": "**AniStream** new version released"
            }
